### ISSUE TITLE
GPU errors

### ISSUE THREAD

**Issue by wenluo711** [NCI-CGR/Nanopore_RNA-seq#1]
- Error message
```
Traceback (most recent call last):
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/venv3/lib/python3.8/site-packages/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/venv3/lib/python3.8/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/venv3/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/venv3/bin/bonito", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/luow2/conda/envs/bonito/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/data/luow2/conda/envs/bonito/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/bonito/__init__.py", line 2, in <module>
    from bonito.cli import basecaller, train, evaluate, view, convert, download, export, duplex
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/bonito/cli/duplex.py", line 37, in <module>
    from bonito.crf.basecall import transfer, split_read, stitch
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/bonito/crf/__init__.py", line 1, in <module>
    from .model import Model
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/bonito/crf/model.py", line 9, in <module>
    import seqdist.sparse
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/venv3/lib/python3.8/site-packages/seqdist/sparse.py", line 10, in <module>
    import cupy as cp
  File "/gpfs/gsfs11/users/luow2/tools/Nanopore_RNA-seq/bonito/venv3/lib/python3.8/site-packages/cupy/__init__.py", line 37, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

```

- Trouble shoot
https://github.com/nanoporetech/bonito/issues/167

- Solution:  Need to start GPU environment first before running bonito 
```
sinteractive --gres=gpu:k80:1,lscratch:10 --mem=20g -c14

```

**Comment by wenluo711** [comment]
Make sure GPU environment is started to run bonito
